version: '3.3'

services:
  zookeeper:
    image: apachepulsar/pulsar-all:latest
    container_name: zookeeper
    hostname: zookeeper
    command: bash -c "bin/apply-config-from-env.py conf/zookeeper.conf && bin/generate-zookeeper-config.sh conf/zookeeper.conf && exec bin/pulsar zookeeper"
    environment:
      - metadataStoreUrl=zk:zookeeper:2181
      - clusterName=cluster-a
      - managedLedgerDefaultEnsembleSize=1
      - managedLedgerDefaultWriteQuorum=1
      - managedLedgerDefaultAckQuorum=1
    ports:
      - 2181:2181
    volumes:
      - ./data/zookeeper:/pulsar/data/zookeeper
    restart: always
    networks: 
      - pulsar
    
  bookie:
    image: apachepulsar/pulsar-all:latest
    container_name: bookie
    hostname: bookie
    command: bash -c "bin/apply-config-from-env.py conf/bookkeeper.conf && exec bin/pulsar bookie"
    environment:
      - zkServers=zookeeper:2181
      - clusterName=cluster-a
      - metadataServiceUri=metadata-store:zk:zookeeper:2181
    ports:
    - 3181:3181
    volumes:
      - ./data/bookkeeper:/pulsar/data/bookkeeper
    restart: always
    depends_on:
      - zookeeper
    networks: 
      - pulsar
      
  pulsar-broker:
    image: apachepulsar/pulsar-all:latest
    container_name: broker
    hostname: broker
    command: bash -c "bin/apply-config-from-env.py conf/broker.conf && exec bin/pulsar broker"
    environment:
      - metadataStoreUrl=zk:zookeeper:2181
      - zookeeperServers=zookeeper:2181
      - clusterName=cluster-a
      - managedLedgerDefaultEnsembleSize=1
      - managedLedgerDefaultWriteQuorum=1
      - managedLedgerDefaultAckQuorum=1
    ports:
      - 6650:6650
      - 8080:8080
    healthcheck:
      test: ["CMD-SHELL", "bin/pulsar-admin brokers healthcheck"]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always
    depends_on:
      - bookie
    networks:
      - pulsar

  pulsar-manager:
    image: apachepulsar/pulsar-manager:v0.3.0
    container_name: pulsar-manager
    hostname: pulsar-manager
    ports:
      - 9527:9527
      - 7750:7750
    depends_on:
      - pulsar-broker
    networks:
      - pulsar
    environment:
      SPRING_CONFIGURATION_FILE: /pulsar-manager/pulsar-manager/application.properties
    volumes:
      - ./data/pulsarmanagerdata:/data
    restart: always

  postgres-ru:
    image: postgres:14
    container_name: postgres-ru
    hostname: postgres-ru
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5430:5432
    networks:
      - pulsar
    restart: always

  postgres-eu:
    image: postgres:14
    container_name: postgres-eu
    hostname: postgres-eu
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5431:5432
    networks:
      - pulsar
    restart: always

  producer:
    container_name: producer
    hostname: producer
    build: ./producer
    ports:
      - 8081:8081
    depends_on:
      - pulsar-broker
    networks:
      - pulsar
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - PULSAR_BROKER=pulsar://broker:6650
      - PULSAR_TOPIC_RU=persistent://public/default/messages-ru
      - PULSAR_TOPIC_EU=persistent://public/default/messages-eu
    restart: always

  consumer-ru-1:
    container_name: consumer-ru-1
    hostname: consumer-ru-1
    build: ./consumer
    ports:
      - 8082:8082
    depends_on:
      - postgres-ru
      - pulsar-broker
    networks:
      - pulsar
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DATABASE_URL=jdbc:postgresql://postgres-ru:5432/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - CONSUMER_REGION=RU
      - CONSUMER_INSTANCE_ID=1
      - PULSAR_SERVICE_URL=pulsar://broker:6650
      - PULSAR_TOPIC=persistent://public/default/messages-ru
    restart: always
    
  consumer-eu-1:
    container_name: consumer-eu-1
    hostname: consumer-eu-1
    build: ./consumer
    ports:
      - 8083:8082
    depends_on:
      - postgres-eu
      - pulsar-broker
    networks:
      - pulsar
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DATABASE_URL=jdbc:postgresql://postgres-eu:5432/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - CONSUMER_REGION=EU
      - CONSUMER_INSTANCE_ID=1
      - PULSAR_SERVICE_URL=pulsar://broker:6650
      - PULSAR_TOPIC=persistent://public/default/messages-eu
    restart: always


networks:
  pulsar:
    driver: bridge
