version: '3.3'

services:
  zookeeper:
    image: apachepulsar/pulsar-all:latest
    container_name: zookeeper
    hostname: zookeeper
    command: bash -c "bin/apply-config-from-env.py conf/zookeeper.conf && bin/generate-zookeeper-config.sh conf/zookeeper.conf && exec bin/pulsar zookeeper"
    environment:
      - metadataStoreUrl=zk:zookeeper:2181
      - clusterName=cluster-a
      - managedLedgerDefaultEnsembleSize=1
      - managedLedgerDefaultWriteQuorum=1
      - managedLedgerDefaultAckQuorum=1
    ports:
      - 2181:2181
    volumes:
      - ./data/zookeeper:/pulsar/data/zookeeper
    restart: always
    networks: 
      - pulsar
    
  bookie:
    image: apachepulsar/pulsar-all:latest
    container_name: bookie
    hostname: bookie
    command: bash -c "bin/apply-config-from-env.py conf/bookkeeper.conf && exec bin/pulsar bookie"
    environment:
      - zkServers=zookeeper:2181
      - clusterName=cluster-a
      - metadataServiceUri=metadata-store:zk:zookeeper:2181
    ports:
    - 3181:3181
    volumes:
      - ./data/bookkeeper:/pulsar/data/bookkeeper
    restart: always
    depends_on:
      - zookeeper
    networks: 
      - pulsar
      
  pulsar-broker:
    image: apachepulsar/pulsar-all:latest
    container_name: broker
    hostname: broker
    command: bash -c "bin/apply-config-from-env.py conf/broker.conf && exec bin/pulsar broker"
    environment:
      - metadataStoreUrl=zk:zookeeper:2181
      - zookeeperServers=zookeeper:2181
      - clusterName=cluster-a
      - managedLedgerDefaultEnsembleSize=1
      - managedLedgerDefaultWriteQuorum=1
      - managedLedgerDefaultAckQuorum=1
    ports:
      - 6650:6650
      - 8080:8080
    healthcheck:
      test: ["CMD-SHELL", "bin/pulsar-admin brokers healthcheck"]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always
    depends_on:
      - zookeeper
      - bookie
    networks:
      - pulsar

  pulsar-manager:
    image: apachepulsar/pulsar-manager:v0.3.0
    container_name: pulsar-manager
    hostname: pulsar-manager
    ports:
      - 9527:9527
      - 7750:7750
    depends_on:
      - pulsar-broker
    networks:
      - pulsar
    environment:
      SPRING_CONFIGURATION_FILE: /pulsar-manager/pulsar-manager/application.properties
    volumes:
      - ./data/pulsarmanagerdata:/data
    restart: always

networks:
  pulsar:
    driver: bridge