BEGIN;

DROP TABLE IF EXISTS CommentContent;
DROP TABLE IF EXISTS Comment;
DROP TABLE IF EXISTS MessageContent;
DROP TABLE IF EXISTS Message;
DROP TABLE IF EXISTS PostContent;
DROP TABLE IF EXISTS Post;
DROP TABLE IF EXISTS Sticker;
DROP TABLE IF EXISTS Video;
DROP TABLE IF EXISTS User_Subscribe;
DROP TABLE IF EXISTS User_tw;
DROP TABLE IF EXISTS Photo;
DROP TABLE IF EXISTS Text;
DROP TABLE IF EXISTS Content;

COMMIT;